// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaFinal.Models;

#nullable disable

namespace PruebaFinal.Migrations
{
    [DbContext(typeof(ClienteDbContext))]
    [Migration("20220329180037_Intaial")]
    partial class Intaial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PruebaFinal.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId_Pais")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Identidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Cliente");

                    b.HasIndex("PaisId_Pais");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PruebaFinal.Models.Pais", b =>
                {
                    b.Property<int>("Id_Pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pais"), 1L, 1);

                    b.Property<string>("Nombre_Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaisId_Pais")
                        .HasColumnType("int");

                    b.HasKey("Id_Pais");

                    b.HasIndex("PaisId_Pais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("PruebaFinal.Models.Cliente", b =>
                {
                    b.HasOne("PruebaFinal.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId_Pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("PruebaFinal.Models.Pais", b =>
                {
                    b.HasOne("PruebaFinal.Models.Pais", null)
                        .WithMany("Paises")
                        .HasForeignKey("PaisId_Pais");
                });

            modelBuilder.Entity("PruebaFinal.Models.Pais", b =>
                {
                    b.Navigation("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
